eureka:
  client:
    register-with-eureka: true # Enables this application to register itself with Eureka
    fetch-registry: true       # Enables this application to fetch the Eureka registry
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka Server
